"""
Train Isolation Forest — Phase 3

Reads data/training_data.csv (generated by prepare_training_data.py),
fits a scikit-learn IsolationForest, and saves the artifact to
models/isolation_forest.joblib along with feature metadata.

Usage:
    python scripts/train_isolation_forest.py

Output:
    models/isolation_forest.joblib  — contains {model, feature_names, midpoints}
"""

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

ROOT = Path(__file__).parent.parent
TRAINING_FILE = ROOT / "data" / "training_data.csv"
OUTPUT_FILE = ROOT / "models" / "isolation_forest.joblib"

# Only train on columns that have sufficient coverage (>= 50 non-null rows)
MIN_COVERAGE = 50

# IsolationForest hyperparameters
N_ESTIMATORS = 200
CONTAMINATION = 0.05   # assume ~5% of training data is anomalous
MAX_SAMPLES = "auto"
RANDOM_STATE = 42


def load_training_data() -> pd.DataFrame:
    df = pd.read_csv(TRAINING_FILE)
    print(f"Loaded: {len(df)} rows x {len(df.columns)} columns")
    return df


def select_features(df: pd.DataFrame) -> list[str]:
    """Keep only columns with sufficient coverage."""
    coverage = df.notna().sum()
    selected = [col for col in df.columns if coverage[col] >= MIN_COVERAGE]
    print(f"\nFeatures selected ({len(selected)} / {len(df.columns)} columns):")
    for col in selected:
        print(f"  {col:25s} {coverage[col]:5d} non-null rows")
    return selected


def compute_midpoints(df: pd.DataFrame, feature_names: list[str]) -> dict[str, float]:
    """Compute per-column midpoints for imputing missing values at inference."""
    midpoints = {}
    for col in feature_names:
        series = df[col].dropna()
        if len(series) > 0:
            midpoints[col] = float(series.median())
        else:
            midpoints[col] = 0.0
    return midpoints


def prepare_matrix(
    df: pd.DataFrame,
    feature_names: list[str],
    midpoints: dict[str, float],
) -> np.ndarray:
    """Fill NaN with column midpoints and return a float matrix."""
    subset = df[feature_names].copy()
    for col in feature_names:
        subset[col] = subset[col].fillna(midpoints[col])
    X = subset.values.astype(float)
    print(f"\nTraining matrix shape: {X.shape}")
    return X


def train(X: np.ndarray) -> tuple[StandardScaler, IsolationForest]:
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    clf = IsolationForest(
        n_estimators=N_ESTIMATORS,
        contamination=CONTAMINATION,
        max_samples=MAX_SAMPLES,
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )
    clf.fit(X_scaled)
    print("IsolationForest training complete.")

    # Quick sanity check
    scores = clf.decision_function(X_scaled)
    print(f"Decision function range on training data: [{scores.min():.4f}, {scores.max():.4f}]")
    print(f"Predicted anomaly fraction: {(clf.predict(X_scaled) == -1).mean():.3f}")
    return scaler, clf


def save(
    scaler: StandardScaler,
    clf: IsolationForest,
    feature_names: list[str],
    midpoints: dict[str, float],
) -> None:
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    artifact = {
        "model": clf,
        "scaler": scaler,
        "feature_names": feature_names,
        "midpoints": midpoints,
    }
    joblib.dump(artifact, OUTPUT_FILE)
    print(f"\nSaved: {OUTPUT_FILE}")


if __name__ == "__main__":
    print("Training Isolation Forest...\n")
    df = load_training_data()
    feature_names = select_features(df)
    midpoints = compute_midpoints(df, feature_names)
    X = prepare_matrix(df, feature_names, midpoints)
    scaler, clf = train(X)
    save(scaler, clf, feature_names, midpoints)
    print("\nDone.")
